### ISSUE TITLE
LightGraphs integration

### ISSUE THREAD

**Issue by sbromberger** [afternone/GraphPlot.jl#1]
Yay, issue #1!

Would you consider integrating this with [LightGraphs](https://github.com/JuliaGraphs/LightGraphs.jl)? We have a couple of graph vis tools there now but we always welcome more.

**Comment by afternone** [comment]
[LightGraphs.jl](https://github.com/JuliaGraphs/LightGraphs.jl) is cool. I have used it for network analysis a few days ago. I will work on it lately.

**Comment by sbromberger** [comment]
Nice! I was looking through your code and it seems like it would be fairly straightforward to support LightGraphs. Please feel free to file an issue there if there's something you need on the LightGraph side.

**Comment by afternone** [comment]
LightGraphs integration is done. Just try it.

**Comment by sbromberger** [comment]
Yes - THIS IS AWESOME. Thank you! I will add to LightGraphs docs as soon as I get a chance.

Here's a 10-node wheelgraph :)

![foo](https://cloud.githubusercontent.com/assets/941359/10552956/4cbe8eea-740c-11e5-94b9-ec868f08310d.png)

**Comment by sbromberger** [comment]
Although I just dug into the code - conversion to a Graphs.jl structure is probably not the best way to integrate to LightGraphs, as it will more than double the memory. Let me take a look at other possible native integrations.

**Comment by afternone** [comment]
When I have time, I will add native interface of LightGraphs.

**Comment by afternone** [comment]
@sbromberger Native interface of LightGraphs is done. If you have any problem, pls let me know, Thanks!

**Comment by sbromberger** [comment]
That's a really elegant way of doing it, @afternone - thanks very much. I'll update the LightGraphs docs today.
