### ISSUE TITLE
spectral_layout gives an error

### ISSUE THREAD

**Issue by juliohm** [afternone/GraphPlot.jl#10]
```julia
using LightGraphs
using GraphPlot

G =  Graph(3)
gplot(G, layout=spectral_layout)
```
>LoadError: MethodError: `_spectral` has no method matching _spectral(::SparseMatrixCSC{Int64,Int64})
while loading In[2], in expression starting on line 5

**Comment by afternone** [comment]
Fix it, try `Pkg.checkout("GraphPlot")`.

**Comment by juliohm** [comment]
Thank you.
