### ISSUE TITLE
nodestrokec has no effect

### ISSUE THREAD

**Issue by Beatzekatze** [afternone/GraphPlot.jl#11]
Hi (and thanks for the fantastic package!)
When using 
```
using Colors
using GraphPlot
g = graphfamous("karate")
gplothtml(g,nodestrokec = RGB(1,0,0))
```
nodes remain as in case when I skip the nodestrokec argument. Am I misunderstanding something or is it a bug? 
EDIT: nevermind; just figured out that nodestroke linewidth is 0 buy default, sorry for creating an issue!

**Comment by afternone** [comment]
Just clean issue.
