### ISSUE TITLE
_src not defined in spectral_layout (nv > 500)

### ISSUE THREAD

**Issue by juliohm** [afternone/GraphPlot.jl#14]
Could you please fix this issue?

>LoadError: UndefVarError: _src not defined
while loading In[10], in expression starting on line 5

 >in spectral_layout at /home/juliohm/.julia/v0.4/GraphPlot/src/layout.jl:238
 in gplot at /home/juliohm/.julia/v0.4/GraphPlot/src/plot.jl:219

**Comment by afternone** [comment]
try instead `_src` and `_dst` with `_src_index` and `_dst_index`. I will fix it when I have time.

**Comment by afternone** [comment]
Issue is fixed, try update.

**Comment by juliohm** [comment]
Thank you, feel free to close the issue. I found another way to explore my
algorithms in the meantime :)

-Júlio
