### ISSUE TITLE
License violation/attribution

### ISSUE THREAD

**Issue by IainNZ** [afternone/GraphPlot.jl#3]
Hi @afternone,

I just saw this code on julia-users. The visualizations look nice. I would like you to make clear that which code, including the spring and stress layout algorithms, have been copied directly from GraphLayouts.jl. In particular, you should adjust your license to make it clear that you do not own that code, and ideally the code would have comments indicating that it is not your work and where it came from.

Thanks!

**Comment by afternone** [comment]
ok, I will add it soon.
