### ISSUE TITLE
Overlapping antiparallel edge labels

### ISSUE THREAD

**Issue by juliohm** [afternone/GraphPlot.jl#4]
See screenshot:

![screenshot from 2016-03-01 13-29-18](https://cloud.githubusercontent.com/assets/3345261/13442578/cef16084-dfb1-11e5-9e1c-9478a74682e9.png)

**Comment by juliohm** [comment]
I tried the option `linetype="curve"` but it is not working (reported in #6)

**Comment by afternone** [comment]
I solved the problem by placing edge labels of directed networks near the arrow (the end of the edge). However, edge labels of undirected networks are still placed at the middle of the edge. Like this
![directed network](https://github.com/afternone/GraphPlot.jl/blob/master/examples/directed_network.jpg)
![undirected network](https://github.com/afternone/GraphPlot.jl/blob/master/examples/undirected_network.jpg)
You can pull the updates and try again.

**Comment by juliohm** [comment]
Thank you @afternone, that is great! I am closing this one.

**Comment by AndyGreenwell** [comment]
By making the change to always place the labels for edges of directed graphs at the edges, the current code no longer provides capability for the user to control the location of edge label placement via the plot function's arguments.
