### ISSUE TITLE
Graph layout changes over multiple runs

### ISSUE THREAD

**Issue by juliohm** [afternone/GraphPlot.jl#5]
If I display the graph in a loop (for debugging an algorithm), the layout changes:

![screenshot from 2016-03-01 13-32-06](https://cloud.githubusercontent.com/assets/3345261/13442690/54abaefa-dfb2-11e5-8580-dd9802494c6a.png)

![screenshot from 2016-03-01 13-32-15](https://cloud.githubusercontent.com/assets/3345261/13442694/58c5b8e6-dfb2-11e5-8e26-b42640b06e62.png)

![screenshot from 2016-03-01 13-32-37](https://cloud.githubusercontent.com/assets/3345261/13442696/5d192bf8-dfb2-11e5-9152-06511fd61298.png)

**Comment by juliohm** [comment]
The only layout that is consistent over multiple runs is the `shell_layout`.

**Comment by afternone** [comment]
You can save the layout coordinates by: `loc_x, loc_y = spring_layout(g)`, and then `gplot(g,  loc_x, loc_y)` using the layout over multiple runs.

**Comment by juliohm** [comment]
Thank you @afternone, this solves the issue for debugging purposes :+1: the layout is consistent within the loop, but is different among different runs still.
