### ISSUE TITLE
ERROR: LoadError: MethodError: `_src_index` has no method matching _src_index(::Graphs.ExEdge{Graphs.ExVertex}, ::Graphs.GenericEdgeList{Graphs.ExVertex,Graphs.ExEdge{V},Array{Graphs.ExVertex,1},Array{Graphs.ExEdge{V},1}})

### ISSUE THREAD

**Issue by rlecover007** [afternone/GraphPlot.jl#8]
I can plot a graph fine using the built in graphs plot, but the gplot command fails with the following error
ERROR: LoadError: MethodError: `_src_index` has no method matching _src_index(::Graphs.ExEdge{Graphs.ExVertex}, ::Graphs.GenericEdgeList{Graphs.ExVertex,Graphs.ExEdge{V},Array{Graphs.ExVertex,1},Array{Graphs.ExEdge{V},1}})
Closest candidates are:
  _src_index{V}(::Graphs.Edge{V}, ::Graphs.AbstractGraph{V,E})
 in graphline at /home/rachel/.julia/v0.4/GraphPlot/src/lines.jl:29
 in gplot at /home/rachel/.julia/v0.4/GraphPlot/src/plot.jl:201
 in gplot at /home/rachel/.julia/v0.4/GraphPlot/src/plot.jl:219

**Comment by afternone** [comment]
try change
 ```
i = _src_index(e, g)
j = _dst_index(e, g)
```
in GraphPlot/src/lines.jl:29 to
```
i = _src_index(e)
j = _dst_index(e)
```

**Comment by afternone** [comment]
try add
```
_src_index{V}(e::Graphs.ExEdge{V}, g::AbstractGraph{V,E}) = Graphs.vertex_index(Graphs.source(e), g)
_dst_index{V}(e::Graphs.ExEdge{V}, g::AbstractGraph{V,E}) = Graphs.vertex_index(Graphs.target(e), g)
```
after GraphPlot/src/GraphPlot.jl:73

**Comment by rlecover007** [comment]
E isn't defined in GraphPlot/src/GraphPlot.jl, so that gets me an error.

**Comment by afternone** [comment]
@rlecover007 Sorry, I forget to add E in the type-declaration field , try change to this
```
_src_index{V,E}(e::Graphs.ExEdge{V}, g::AbstractGraph{V,E}) = Graphs.vertex_index(Graphs.source(e), g)
_dst_index{V,E}(e::Graphs.ExEdge{V}, g::AbstractGraph{V,E}) = Graphs.vertex_index(Graphs.target(e), g)
```

**Comment by rlecover007** [comment]
That fixed it. Thanks!
