### ISSUE TITLE
Edges aren't drawn in output file

### ISSUE THREAD

**Issue by juliohm** [afternone/GraphPlot.jl#9]
Consider the following graph correctly displayed in a Jupyter notebook with `display`:

![screenshot from 2016-04-17 13-53-06](https://cloud.githubusercontent.com/assets/3345261/14589966/d170b500-04a3-11e6-95bc-5eb427d97408.png)

When I try to save the graph to a file, the edges disappear:

```julia
draw(SVG("foo.svg", 16cm, 16cm), gplot(G))
```

There is an easy fix to this issue? I am preparing a presentation by the end of the week and I would like to include a GIF of the graph algorithm in action.

**Comment by afternone** [comment]
Everything is ok on my PC. You can try `Pkg.checkout("GraphPlot")` and draw it again.

**Comment by juliohm** [comment]
@afternone I did `Pkg.update()` but I still can't see the edges. This is the algorithm in action without edges:

![graph](https://cloud.githubusercontent.com/assets/3345261/14591573/bb174010-04c8-11e6-8f0f-a1a29d0e2b0e.gif)

**Comment by afternone** [comment]
Can you show the snippet for a simple example?

**Comment by juliohm** [comment]
I found the issue, it is not the `draw`, but the `display` that I am calling immediately before the `draw`. Is it somehow affecting the plot object that I am passing to it? Trying to write a minimal reproducible example...

**Comment by juliohm** [comment]
@afternone it will take some time to produce a minimal example reproducing the issue. Do you have any idea of why the flip of lines `display` and `draw` is affecting the result?

**Comment by afternone** [comment]
Function `display` does not affect the passing plot object. Try the following example:
```
using Graphs
using GraphPlot
g = Graphs.simple_graph(3, is_directed=true)
add_edge!(g, 1, 2)
add_edge!(g, 2, 3)
add_edge!(g, 3, 1)
display(gplot(g))
draw(SVG("test.svg", 16cm, 16cm), gplot(g))
```
This minimal example is fine on my PC.

**Comment by juliohm** [comment]
@afternone this example is also fine on my PC. I don't know what exactly was the issue, but now that I solved it by flipping the lines of code with `display()` and `draw()` I will close this one and wait for it to appear again in the future. Thank you for all the support.
